name: Build RFID-Connector ESP32-DEV-PCB_V1.0 Firmware

on:
  push:
    branches:
      - main
      - 'feat/*'
    paths:
      - 'RFID-Connector/**'
      - '.github/workflows/build-RFID-Connector-ESP32-DEV-PCB_V1.0.yml'
      - 'dev-tools/github-workflow-files/flasher/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
        # Optional: token: ${{ secrets.GITHUB_TOKEN }} falls für private Repos oder Push nötig

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        #with:
        #  version: 0.35.0 # Unbedingt diese Versionsangabe verwenden!

      - name: Install ESP32 Board Manager
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install ArduinoWebsockets Library
        run: |
          arduino-cli lib install "ArduinoWebsockets"

      - name: Install ArduinoJson Library
        run: |
          arduino-cli lib install "ArduinoJson"

      - name: Modify Sketch Defines
        run: |
          CONFIG_FILE="./RFID-Connector/RFID-Connector.ino" # Pfad Ino-File
          echo "Passe ESP32-Definitionen in ${CONFIG_FILE} an..."

          # Zeile '#define RFID_Connector_PCB_V1_0' aktivieren (entkommentieren, falls auskommentiert)
          sed -i 's/^[[:space:]]*\/\/#[[:space:]]*define RFID_Connector_PCB_V1_0/#define RFID_Connector_PCB_V1_0/g' "${CONFIG_FILE}"
          echo "-> '#define RFID_Connector_PCB_V1_0' aktiviert."

          # Optional: Aenderungen im Log anzeigen
          echo "Angepasster Sketch-Inhalt (Auszug Definitionen):"
          grep -E "define RFID_Connector_PCB_V1_0" "${CONFIG_FILE}" || true

      - name: Compile ESP32 Sketch
        run: |
          # Define a clear build output directory
          BUILD_OUTPUT_DIR="build_output"
          
          arduino-cli compile --fqbn esp32:esp32:esp32 --build-path ${BUILD_OUTPUT_DIR} ./RFID-Connector/

      - name: Create Artifact Directory
        run: |
          SUB_DIR="RFID-Connector-ESP32-DEV"
          mkdir -p artifact_package/${SUB_DIR}/bin
          mkdir -p artifact_package/${SUB_DIR}/windows
          mkdir -p artifact_package/${SUB_DIR}/linux
        #mkdir -p artifact_package/${SUB_DIR}/osx

      - name: Move compiled binaries to Artifact Directory
        run: |
          BUILD_OUTPUT_DIR="build_output"
          SUB_DIR="RFID-Connector-ESP32-DEV"
          TARGET_BIN_DIR="./artifact_package/${SUB_DIR}/bin"
          INO_FILE="RFID-Connector.ino"
          find ./${BUILD_OUTPUT_DIR}/ -name "${INO_FILE}.bin" -exec mv {} ${TARGET_BIN_DIR}/ \;
          find ./${BUILD_OUTPUT_DIR}/ -name "${INO_FILE}.bootloader.bin" -exec mv {} ${TARGET_BIN_DIR}/ \;
          find ./${BUILD_OUTPUT_DIR}/ -name "${INO_FILE}.partitions.bin" -exec mv {} ${TARGET_BIN_DIR}/ \;
          find ~ -name "boot_app0.bin" -exec mv {} ${TARGET_BIN_DIR}/ \;

      - name: copy esptool and Flash Scripts to Artifact Package
        run: |
          SUB_DIR="RFID-Connector-ESP32-DEV"
          cp ./dev-tools/github-workflow-files/flasher/windows/ESP32-DEV_RFID-Connector.ps1 ./artifact_package/${SUB_DIR}/windows/
          cp ./dev-tools/github-workflow-files/flasher/windows/esptool.exe ./artifact_package/${SUB_DIR}/windows/
          cp ./dev-tools/github-workflow-files/flasher/windows/README.md ./artifact_package/${SUB_DIR}/windows/
          cp ./dev-tools/github-workflow-files/flasher/linux/ESP32-DEV_RFID-Connector.sh ./artifact_package/${SUB_DIR}/linux/
          cp ./dev-tools/github-workflow-files/flasher/linux/esptool ./artifact_package/${SUB_DIR}/linux/
        #cp ./dev-tools/github-workflow-files/flasher/osx/ESP32-DEV_RFID-Connector.sh ./artifact_package/${SUB_DIR}/osx/
        #cp ./dev-tools/github-workflow-files/flasher/osx/esptool ./artifact_package/${SUB_DIR}/osx/

      - name: lst package content
        run: |
          echo "Content of Artefakt-Package:"
          ls -lR ./artifact_package/

      - name: Generate Timestamp
        id: timestamp_gen
        run: echo "BUILD_DATE=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Upload Binaries as Artifact
        uses: actions/upload-artifact@v4
        with:
          path: artifact_package
          #name: ${{ steps.timestamp_gen.outputs.BUILD_DATE }}-RFID-Connector-ESP32-DEV-PCB_V1.0
          name: RFID-Connector-ESP32-DEV-PCB_V1.0
          retention-days: 7